awslabs/agent-squad

docs/src/content/docs/advanced-features/agent-overlap.md

<details>
Checklist:
</details>

update doc - overlap

---

src/agents/agent.ts
src/classifiers/anthropicClassifier.ts
src/classifiers/bedrockClassifier.ts
src/classifiers/classifier.ts
src/orchestrator.ts
src/types/index.ts
src/utils/logger.ts

Cleaning export from types to respective class

seperated definitions into respective classes

---

typescript/package.json

<details>
Checklist:
</details>

increase ts version

---

.gitignore
README.md
examples/chat-demo-app/.gitignore
examples/chat-demo-app/lambda/multi-agent/math_tool.ts
examples/chat-demo-app/lambda/multi-agent/weather_tool.ts
examples/local-demo/local-orchestrator.ts
examples/local-demo/package.json
examples/local-demo/tools/math_tool.ts
examples/local-demo/tools/weather_tool.ts

updating quickstart as well as fixing .gitignore files

Doc update

---

docs/astro.config.mjs
docs/src/content/docs/agents/examples/ollama-agent.md
examples/local-demo/ollamaAgent.ts

Ollama agent

---

examples/chat-demo-app/user-interface/package-lock.json
examples/chat-demo-app/user-interface/package.json

fix security issues

---

docs/src/content/docs/storage/dynamodb.md
docs/src/content/docs/storage/in-memory.md

fixed documentation about ChatStorage

---

typescript/src/index.ts

Added missing export to be able to create a custom Classifier

added missing export for custom Classifier

---

typescript/package.json

increased version before release

increased version

---

docs/src/content/docs/retrievers/custom-retriever.md

fixed documentation

---

docs/src/content/docs/classifiers/overview.mdx
docs/src/content/docs/orchestrator/overview.mdx

<details>
Checklist:
</details>

update doc for classifier and orchestrator

---

python/src/multi_agent_orchestrator/agents/bedrock_llm_agent.py

**Issue number:*#49*
I simply adapted the code with documentation around bedrock converse stream.
Cf documentation : https://docs.aws.amazon.com/bedrock/latest/userguide/tool-use-examples.html
<details>
Checklist:
</details>

Handle streaming on Agent with toolConfig enable

---

python/src/multi_agent_orchestrator/utils/logger.py

<details>
Checklist:
</details>

Change to second unit instead of millisecond

---

docs/src/content/docs/agents/examples/ollama-agent.mdx
examples/chat-chainlit-app/.gitignore
examples/chat-chainlit-app/README.md
examples/chat-chainlit-app/agents.py
examples/chat-chainlit-app/app.py
examples/chat-chainlit-app/chainlit.md
examples/chat-chainlit-app/ollamaAgent.py
examples/chat-chainlit-app/orchestrator.py
examples/chat-chainlit-app/requirements.txt

A Chainlit Chat demo app with 3 agents
Added details in README.md

chainlit demo app with 3 agents

---

python/src/multi_agent_orchestrator/agents/bedrock_llm_agent.py

> Removing duplicated instructions
<details>
Checklist:
</details>

Saving few tokens.

---

python/src/multi_agent_orchestrator/agents/amazon_bedrock_agent.py
python/src/multi_agent_orchestrator/storage/in_memory_chat_storage.py

Fixed agentId not populated in history section of the prompt for classifier when using in memory storage

---

typescript/src/agents/amazonBedrockAgent.ts
typescript/src/orchestrator.ts

Added support for sessionState in Agents for Bedrock TS

---

python/src/multi_agent_orchestrator/storage/in_memory_chat_storage.py

Fixed in-memory

---

python/setup.cfg
typescript/src/classifiers/openAIClassifier.ts
typescript/tests/classifiers/OpenAIClassifier.test.ts

fixed ts lint and test

---

docs/src/content/docs/general/faq.md

> framwork -> framework
<details>
Checklist:
</details>

docs: update faq.md

---

docs/src/content/docs/cookbook/examples/chat-demo-app.md

doc update for chat-demo app deployment

updated doc for cdk bootstrap and deployment

---

docs/package-lock.json
docs/src/content/docs/agents/built-in/amazon-bedrock-agent.mdx
python/src/multi_agent_orchestrator/agents/amazon_bedrock_agent.py
python/src/tests/agents/test_amazon_bedrock_agent.py
typescript/package-lock.json
typescript/src/agents/amazonBedrockAgent.ts

Added support for Bedrock Agents streaming and trace for both TS and python.
See #118

Bedrock agents streaming

---

typescript/src/index.ts

**Issue number:** #158
Add export for BedrockInlineAgentOptions and BedrockInlineAgent
Add export for BedrockInlineAgentOptions and BedrockInlineAgent
NA
<details>
Checklist:
</details>

fix: add export for BedrockInlineAgent and BedrockInlineAgentOptions

---

docs/src/content/docs/agents/built-in/anthropic-agent.mdx
docs/src/content/docs/agents/built-in/bedrock-flows-agent.mdx
docs/src/content/docs/agents/built-in/openai-agent.mdx
docs/src/content/docs/cookbook/tools/math-operations.md
docs/src/content/docs/cookbook/tools/weather-api.mdx

This change updates some minor code formatting issues in the documentation such as indentions, line breaks, and unnecessary spaces. The intention is to provide consistent code examples across the project.
No actual code in the examples was changed.
Documentation code formatting -- specifically to the Typescript examples.
An example page with 4 spaces as indentions https://awslabs.github.io/multi-agent-orchestrator/cookbook/tools/math-operations/. This PR would replace those with 2 spaces to match the project.
<details>
Checklist:
</details>
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

minor documentation formatting

---

python/src/multi_agent_orchestrator/agents/agent.py
python/src/multi_agent_orchestrator/agents/amazon_bedrock_agent.py
python/src/multi_agent_orchestrator/agents/bedrock_llm_agent.py
python/src/multi_agent_orchestrator/agents/lex_bot_agent.py
python/src/tests/agents/test_agent.py
typescript/package-lock.json
typescript/src/agents/agent.ts
typescript/src/agents/bedrockLLMAgent.ts

<details>
Checklist:
</details>

remove useless field in Agent

---

python/src/multi_agent_orchestrator/storage/chat_storage.py
python/src/multi_agent_orchestrator/storage/dynamodb_chat_storage.py
python/src/multi_agent_orchestrator/storage/in_memory_chat_storage.py
python/src/multi_agent_orchestrator/storage/sql_chat_storage.py
python/src/tests/storage/test_chat_storage.py

<details>
Checklist:
</details>

rename function & update tests

---

docs/src/content/docs/cookbook/examples/ollama-classifier.mdx
docs/src/content/docs/orchestrator/overview.mdx
python/src/multi_agent_orchestrator/orchestrator.py
typescript/src/orchestrator.ts
typescript/tests/Orchestrator.test.ts

<details>
Checklist:
</details>

remove method

---

docs/src/content/docs/storage/sql.mdx

removed duplicate content in docs
users won't see duplicate local DB heading in SQL storage docs
<details>
<summary>Is this a breaking change? no</summary>
Checklist:
</details>

cleanup duplicate content

---

docs/src/content/docs/general/quickstart.mdx

<details>
Checklist:
</details>

Fix broken link in Quickstart Guide

---

python/src/multi_agent_orchestrator/agents/supervisor_agent.py

<details>
Checklist:
</details>

send additional_params to each agent in the team

---

README.md

<details>
Checklist:
</details>

remove star history, throttled

---

python/setup.cfg

<details>
Checklist:
</details>

update min version required for libs

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/pr-issue-link-checker.yml
README.md

<details>
Checklist:
</details>

enforce PR to be linked to an issue

---

typescript/package.json
typescript/src/agents/amazonBedrockAgent.ts
typescript/src/agents/bedrockFlowsAgent.ts
typescript/src/agents/bedrockLLMAgent.ts
typescript/src/agents/lambdaAgent.ts
typescript/src/agents/lexBotAgent.ts
typescript/src/classifiers/bedrockClassifier.ts
typescript/src/common/src/awsSdkUtils.ts
typescript/src/common/src/types/awsSdk.ts
typescript/src/common/src/version.ts
typescript/src/index.ts

added support for custom user agent in TS

---

.github/workflows/py-run-tests.yml
.github/workflows/ts-run-tests.yml
python/CONTRIBUTING.md
python/Makefile
python/ruff.toml
python/test_requirements.txt

Fixes #302 
This PR introduces `Ruff` as the code linting and formatting tool and configures a new CI pipeline step to ensure code quality standards. 
- Added Ruff as a development dependency
- Created a basic configuration file for Ruff
- Added a new step in the CI pipeline to run code quality checks
- Updated documentation with information about the new code quality requirements
- Added a Makefile to standardize development commands
Currently, no specific linting rules or formatting checks have been enabled. Additional PRs will follow to gradually implement specific rules and formatting standards based on maintainer consensus.
Moving forward, all PRs must comply with the code standards established by Ruff. The CI pipeline will now enforce these standards automatically.
I recommend …

chore(ci): integrate Ruff for code linting and formatting in CI pipeline

---

README.md

Animated Workflow Diagram Added to understand flow how it works

Animated Diagram Added

---

README.md

Reverts awslabs/agent-squad#332

Revert "Animated Diagram Added"

---

docs/src/content/docs/agents/built-in/anthropic-agent.mdx
docs/src/content/docs/agents/tools.mdx
docs/src/content/docs/general/faq.md
examples/fast-api-streaming/README.MD

Fixes  #342
Thank you for creating this project. While reading through the documentation, I noticed a few minor typos and a small inconsistency. This PR fixes those issues.
A few instances of incorrect articles (e.g., "a" instead of "an") have been changed.
A typo in the word "handler" (written as "hanlder") have been resolved.
A section that mentions three classes for AgentTools, but only two are currently listed, has been addressed.
Please let me know if you'd prefer a different approach.
The User should experience a minor improvement in reading the documentation. 
<details>
Checklist:
</details> No
By submitting this pull request, I confirm that you can …

Fix some minor typos in the documentation. 

---

examples/python/readme.md

Fixes #
<details>
Checklist:
</details>

Update path in Python examples documentation

---

typescript/src/classifiers/classifier.ts

Fixes #354 
Fixing typo
Before - Typo
After - No typo
<details>
No
Checklist:
</details>

fix classifier prompt typo
